### ISSUE TITLE
different file formats

### ISSUE THREAD

**Issue by stonecrusher** [dVaffection/cuegenerator#10]
Thank you for the nice script and making it available online!

Two little issues:

- A dropdown selection for the different [allowed file formats](https://web.archive.org/web/20160201021136/http://digitalx.org/cue-sheet/syntax/#file) would be convenient (MP3, WAVE, AIFF, BINARY, MOTOROLA)

- Typo on the homepage "leave an issue on G**u**tHub"

**Comment by dVaffection** [comment]
PR was created #11 . I'm waiting for @lindmik reply

**Comment by stonecrusher** [comment]
Wow, thanks! That was really fast and no discussion. I don't think anyone uses AIFF or MOTOROLA anymore, but I'd keep them.

Be aware you named that file `main-built.2018-01-03.js` at several places. Happy New Year :-)

**Comment by dVaffection** [comment]
Yea it's not a big change. I hope @lindmik will help me with a deploy. 

Regarding `main-built.2018-01-03.js` file name. I specify it in the build config and then I need to reference it via the script tag -- the only purpose so the browser doesn't take it from cache.

**Comment by lindmik** [comment]
I'm away from my computer for a while. @frifox should ve able to help you deploy the changes.

**Comment by frifox** [comment]
production is on master branch, merge changes and I can deploy (if it's just a simple git pull, otherwise I may need some further directions on how to deploy)

**Comment by frifox** [comment]
also, there are quite a few unstaged changes on production that aren't in repo:

    Changes not staged for commit:

	modified:   scripts/cue/parser.js
	modified:   scripts/main-built.2015-10-23-02.js
	modified:   scripts/tests/parser.js

    Untracked files:

	400.shtml
	401.shtml
	403.shtml
	404.shtml
	500.php
	500.shtml
	backup/
	default.html
	error_log

**Comment by dVaffection** [comment]
@frifox I merged my PR. 
Can you diff those files? Cause changed files look very much like @lindmik's PR #9

**Comment by dVaffection** [comment]
But you probably can ignore them cause the aforementioned PR #9 is in master

**Comment by frifox** [comment]
pushed those changes to "unstaged" branch, feel free to compare

**Comment by dVaffection** [comment]
Let's move discussion to the #12

**Comment by dVaffection** [comment]
And deployed! Thx @frifox

**Comment by GB-CG** [comment]
Any chance of FLAC being included?

**Comment by dmitry-bluescape** [comment]
@frifox @lindmik pls re-deploy `master` -- I added FLAC

**Comment by dVaffection** [comment]
@frifox  @lindmik  pls re-deploy master -- I added FLAC

**Comment by GB-CG** [comment]
I forgot to mention, ALAC & AAC would be nice too.

**Comment by dmitry-bluescape** [comment]
How are we ordering them? Does it even matter? I feel like MP3 should go first but then ¯\_(ツ)_/¯

**Comment by dVaffection** [comment]
How are we ordering them? Does it even matter? I feel like MP3 should go first but then ¯_(ツ)_/¯

**Comment by GB-CG** [comment]
Maybe something like this, I quite like this one:
<details><summary>Order list</summary>

```
FLAC
WAVE
AIFF
ALAC
AAC
MP3
MOTOROLA
BINARY
```

</details>

I'm more of a FLAC/AAC guy myself, but it's your call.

**Comment by dVaffection** [comment]
I added ALAC & AAC and sorted a list in abc order with MP3 goes first. Waiting for a deploy
