### ISSUE TITLE
Increase max minutes

### ISSUE THREAD

**Issue by RPM7** [dVaffection/cuegenerator#14]
First, thank you for your work.
Any chance to increase the max minutes from 999 minutes to 9999? I make cue sheets for my audiobooks and a lot of them have more than 999 minutes.
Thanks in advance!

**Comment by dVaffection** [comment]
Yes it's an easy task. But I'm quite busy this week. If I don't do that this week please ping next week @RPM7

**Comment by dVaffection** [comment]
Changes in the `master`, waiting for @frifox deploy

**Comment by RPM7** [comment]
@dVaffection Still no changes

**Comment by dVaffection** [comment]
pinging @frifox for deploy

**Comment by dmitry-bluescape** [comment]
@RPM7 may I ask for an example?

**Comment by dVaffection** [comment]
@RPM7 can you gimme an example? Maybe I misunderstood your request ¯\_(ツ)_/¯

**Comment by RPM7** [comment]
I use cue generator to split my audiobooks, some of them have more than 999:00:00 minutes. The site doesn't support times above 999 minutes. So for example, if I want a track at 1020:00:00, it ignores the 4th minute and displays 020:00:00. My request is to have 4 digits instead of three, being the max minutes 9999:00:00 instead of 999:00:00.

**Comment by RPM7** [comment]
@dVaffection

**Comment by dVaffection** [comment]
I'm still not quite sure as it works for me. Do you have as different experience?

<img width="1012" alt="I'm still not quite sure as it works for me" src="https://user-images.githubusercontent.com/457097/69185501-b9cbc700-0acb-11ea-942b-9f10a92f19de.png">

**Comment by RPM7** [comment]
@dVaffection 1. Are you supposed to enter the timings in "tracklist" or in "timing" box? I have always entered the timings in "timings" box.
2. If I understand it right when you enter the times in "tracklist" it multiplies the first number by 60, but in the "timings" it does not. for example if I enter 99:40:40 in "timings" it will display the same 99:40:40, but if I enter the same 99:40:40 in "tracklist" it will display 5980:40:00.
3. The "tracklist" box is not precise as the "timings" box. In the "tracklist" the miliseconds always show 00, as you can see in the example above.
4. if you enter 1000:00:00+ in the "tracklist" box, it stops multiplyiing by 60, as it shows in your previous answer screenshot.
5. I think the modifications were made in the "tracklist box" instead of the "timings" box.

**Comment by RPM7** [comment]
@dVaffection

**Comment by dVaffection** [comment]
"timings" box works for certain application outputs -- they're listed on the [help page](http://cuegenerator.net/help.html)
