### ISSUE TITLE
Fantastic! How can i get it to work with Audition Marker CSV export?

### ISSUE THREAD

**Issue by nuphunk** [dVaffection/cuegenerator#15]
This is so close to being really useful to me. Thank you for sharing your work!
I use Audition and am trying to export markers to CSV then copying from excel - but the time format exported is:

58:23.855

and i think it expects 00:58:23 and therefore doesn't work as a workflow - real shame!

Any ideas around this issue (i'm mac based so that app you recommended for Audition won't work)

Thanks!
Pete

**Comment by dVaffection** [comment]
Can you try to change display format to 75 frames and see if it makes a difference for export timings? Here's a help link https://helpx.adobe.com/audition/using/navigating-time-playing-audio.html

**Comment by nuphunk** [comment]
Awesome - so cool, at last! Thanks so much.

**Comment by nuphunk** [comment]
Spoke to soon! The times don't correspond. The only way i can get it to work is to strip the last 3 digits with 
=LEFT(B1;8)
In excel.

**Comment by dVaffection** [comment]
Can you show me your output?

**Comment by nuphunk** [comment]
[Markers_75.csv.zip](https://github.com/dVaffection/cuegenerator/files/4005310/Markers_75.csv.zip)

**Comment by dVaffection** [comment]
<img width="719" alt="Screen Shot 2020-04-14 at 11 09 22 PM" src="https://user-images.githubusercontent.com/457097/79304128-6bb5c680-7ea5-11ea-8325-d46128686063.png">
