### ISSUE TITLE
The first index of a file must start at 00:00:00

### ISSUE THREAD

**Issue by ha-korth** [dVaffection/cuegenerator#19]
When TRACK 01 INDEX 01 does not start at 00:00:00 (e.g. 00:00:32) the line should be preceded with the line `INDEX 00 00:00:00` to show the start of the file.

https://web.archive.org/web/20160123204637/http://www.digitalx.org/cue-sheet/syntax/#indx

https://web.archive.org/web/20070614044112/http://www.goldenhawk.com/download/cdrwin.pdf (see Appendix A - INDEX command)

![cuegenerator_1](https://user-images.githubusercontent.com/36651918/103828091-5b073b00-5048-11eb-94fc-6bc1364f9670.jpg)

**Comment by dVaffection** [comment]
Hi @ha-korth,

This issue has been around for some time. Have you manage to circumvent it?

**Comment by ha-korth** [comment]
I manually edit of the CUE after it is saved by cuegenerator

> PERFORMER "Eric Clapton"
> TITLE "August"
> FILE "Eric Clapton - August.wav" WAVE
>   TRACK 01 AUDIO
>     PERFORMER "Eric Clapton"
>     TITLE "It’s in the Way That You Use It"
>     INDEX 01 00:00:32
>   [...]

becomes

> PERFORMER "Eric Clapton"
> TITLE "August"
> FILE "Eric Clapton - August.wav" WAVE
>   TRACK 01 AUDIO
>     PERFORMER "Eric Clapton"
>     TITLE "It’s in the Way That You Use It"
>     INDEX 00 00:00:00
>     INDEX 01 00:00:32
>   [...]

**Comment by dVaffection** [comment]
The fix is in the master, waiting for deploy @frifox

**Comment by frifox** [comment]
deployed

**Comment by dVaffection** [comment]
My bad I forgot to make a new build. please deploy again
