### ISSUE TITLE
Website has a ribbon "Find me on github"  Save button not working

### ISSUE THREAD

**Issue by Tomtreas** [dVaffection/cuegenerator#20]
Please reinstate functionality of your website or are you going to take it down completely?  I'm guessing that I can install the code on my own server and it will work the same?
![Screenshot 2021-02-19 205735](https://user-images.githubusercontent.com/76670586/108581751-251acf00-72f5-11eb-8fbe-a3154b45d714.png)

**Comment by dVaffection** [comment]
Hi @Tomtreas, could you point out what exactly is not functioning?

**Comment by Tomtreas** [comment]
I cannot click on the save button or anything under what that ribbon
touches thereby breaking the function of the site.  I had to find another
way to make my cue sheets this week.  Love the way yours works.

**Comment by daniel-rikowski** [comment]
This only happens on small screens, perhaps this screenshot with visible developer tools shows the problem:

![grafik](https://user-images.githubusercontent.com/1169363/108621580-c3ad4a00-7433-11eb-8b70-68741a46d278.png)

Adding a negative z-index to `.github-fork-ribbon-wrapper` looks ugly, but at least the button is clickable.

**Comment by dVaffection** [comment]
I see this is an issue on smaller screens. I removed the GitHub ribbon altogether cause there's already a link to GitHub. 

@frifox please redeploy
